name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: paulw02
          password: Adda2002!
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .  # Path to the Docker context (usually the root of your repository)
          push: true   # Whether to push the built image
          tags: |
            paulw02/login-microservice-image:latest
