name: GitHub Actions Demo

on:
  push:
    branches:
      - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: paulw02
          password: dckr_pat_YyCDVGuBu5evnlk_KPT-H7ivWdU
      - name: Build and Run Docker Container
        run: |
          docker buildx build --platform linux/amd64 -t paulw02/login-microservice-image .
          docker run -p 5001:5001 --name login paulw02/login-microservice-image
